name: CUSTOM-UI
on:
  push:
    branches: [custom-ui]
    tags:
    - 'v*'

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Docker login
      if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master') && success()
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker build & tag
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      run:
        DOCKER_BUILDKIT=1 docker build --no-cache -t ${{ secrets.RANCHER_CUSTOM }}:${GITHUB_REF/refs\/tags\//} ${{ secrets.RANCHER_CUSTOM_PATH }}
    - name: Docker push
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      run:
        docker push ${{ secrets.RANCHER_CUSTOM }}:${GITHUB_REF/refs\/tags\//}
    - name: Docker Hub Description
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
      uses: peter-evans/dockerhub-description@v2.0.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: ${{ secrets.RANCHER_CUSTOM }}
